### ISSUE TITLE
Coding error when calling file_rewrite_pluginfile_urls()

### ISSUE THREAD

**Issue by mudrd8mz** [IPA-Lets-Study-Together/moodle-booktool_download#6]
When attempting to generate the PDF, I am getting the following error:

```
Coding error detected, it must be fixed by a programmer: PHP catchable fatal error

Debug info: Object of class stdClass could not be converted to string
Error code: codingerror
Stack trace:

line 393 of /lib/setuplib.php: coding_exception thrown
line 475 of /lib/filelib.php: call to default_error_handler()
line 162 of /mod/book/tool/download/lib.php: call to file_rewrite_pluginfile_urls()
line 44 of /mod/book/tool/download/index.php: call to generate_pdf()
```

Please check the `$chapterid` as it does not contain the id but the full record as returned by the database. You may wish to fix it by something like
`foreach (array_keys($chapterids) as $chapterid) {` at the line 139 (note that it still leads to a PHP notice in another place so PDF can not be downloaded).

**Comment by ghost** [comment]
It seems to work fine after closing #4
