### ISSUE TITLE
DB queries in the PHP loop

### ISSUE THREAD

**Issue by mudrd8mz** [IPA-Lets-Study-Together/moodle-booktool_download#7]
The function that generates the PDF calls DB queries in the PHP loop. This is generally considered as a very bad practise for performance and DB load. Please consider using constant count of DB calls. I believe you can load the required data in one query here and than loop over the returned recordset. See https://docs.moodle.org/dev/Data_manipulation_API#Using_Recordsets for details.

**Comment by ghost** [comment]
Thank you for your suggestion. This solution is much better.
